server:
  port: 8088



logging:
  level:
    org.springframework: DEBUG


spring:
  jpa:
    show-sql: true

  messages:
    basename: messages

  h2:
    console:
      enabled: true

#  security:
#    user:
#      name: username
#      password: passw0rd


manaagement:
  endpoints:
    web:
      exposure:
        include: "*"